name: Build Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #Needed to build image
      packages: write #Needed to publish package/image

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Image
      run: |
            docker build . --file Dockerfile --tag ghcr.io/roboflow/roboflow-react-app:latest
            docker push ghcr.io/roboflow/roboflow-react-app:latest